[development]
address = "localhost"
port = 8000
log = "debug"
workers = 16

[production]
address = "0.0.0.0"
port = 80
workers = 4
log = "critical"
secret_key = "LGnnqz5VyZlt1Bh+1znlX6WbJtL/j0cUp71L1bnlPDI="

[development.databases.primary_db]
url = "postgres://k8s-user:password@localhost/k8s"
