[development]
address = "localhost"
port = 8000
workers = 16

[production]
address = "0.0.0.0"
port = 80
workers = 4
log = "critical"

[development.databases.primary_db]
url = "postgres://k8s-user:password@localhost/k8s"
